/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DeviceEncryption - struct for DeviceEncryption
type DeviceEncryption struct {
	Aes128 *Aes128
	Aes256 *Aes256
}

// Aes128AsDeviceEncryption is a convenience function that returns Aes128 wrapped in DeviceEncryption
func Aes128AsDeviceEncryption(v *Aes128) DeviceEncryption {
	return DeviceEncryption{
		Aes128: v,
	}
}

// Aes256AsDeviceEncryption is a convenience function that returns Aes256 wrapped in DeviceEncryption
func Aes256AsDeviceEncryption(v *Aes256) DeviceEncryption {
	return DeviceEncryption{
		Aes256: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeviceEncryption) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Aes128
	err = newStrictDecoder(data).Decode(&dst.Aes128)
	if err == nil {
		jsonAes128, _ := json.Marshal(dst.Aes128)
		if string(jsonAes128) == "{}" { // empty struct
			dst.Aes128 = nil
		} else {
			if err = validator.Validate(dst.Aes128); err != nil {
				dst.Aes128 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Aes128 = nil
	}

	// try to unmarshal data into Aes256
	err = newStrictDecoder(data).Decode(&dst.Aes256)
	if err == nil {
		jsonAes256, _ := json.Marshal(dst.Aes256)
		if string(jsonAes256) == "{}" { // empty struct
			dst.Aes256 = nil
		} else {
			if err = validator.Validate(dst.Aes256); err != nil {
				dst.Aes256 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Aes256 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Aes128 = nil
		dst.Aes256 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeviceEncryption)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DeviceEncryption)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeviceEncryption) MarshalJSON() ([]byte, error) {
	if src.Aes128 != nil {
		return json.Marshal(&src.Aes128)
	}

	if src.Aes256 != nil {
		return json.Marshal(&src.Aes256)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeviceEncryption) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Aes128 != nil {
		return obj.Aes128
	}

	if obj.Aes256 != nil {
		return obj.Aes256
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DeviceEncryption) GetActualInstanceValue() (interface{}) {
	if obj.Aes128 != nil {
		return *obj.Aes128
	}

	if obj.Aes256 != nil {
		return *obj.Aes256
	}

	// all schemas are nil
	return nil
}

type NullableDeviceEncryption struct {
	value *DeviceEncryption
	isSet bool
}

func (v NullableDeviceEncryption) Get() *DeviceEncryption {
	return v.value
}

func (v *NullableDeviceEncryption) Set(val *DeviceEncryption) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceEncryption) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceEncryption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceEncryption(val *DeviceEncryption) *NullableDeviceEncryption {
	return &NullableDeviceEncryption{value: val, isSet: true}
}

func (v NullableDeviceEncryption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceEncryption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


