/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceEncryptionAes256 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceEncryptionAes256{}

// DeviceEncryptionAes256 struct for DeviceEncryptionAes256
type DeviceEncryptionAes256 struct {
	// A 64-character hexadecimal string.
	Passcode string `json:"passcode" validate:"regexp=^[a-fA-F0-9]+$"`
}

type _DeviceEncryptionAes256 DeviceEncryptionAes256

// NewDeviceEncryptionAes256 instantiates a new DeviceEncryptionAes256 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceEncryptionAes256(passcode string) *DeviceEncryptionAes256 {
	this := DeviceEncryptionAes256{}
	this.Passcode = passcode
	return &this
}

// NewDeviceEncryptionAes256WithDefaults instantiates a new DeviceEncryptionAes256 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceEncryptionAes256WithDefaults() *DeviceEncryptionAes256 {
	this := DeviceEncryptionAes256{}
	return &this
}

// GetPasscode returns the Passcode field value
func (o *DeviceEncryptionAes256) GetPasscode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passcode
}

// GetPasscodeOk returns a tuple with the Passcode field value
// and a boolean to check if the value has been set.
func (o *DeviceEncryptionAes256) GetPasscodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passcode, true
}

// SetPasscode sets field value
func (o *DeviceEncryptionAes256) SetPasscode(v string) {
	o.Passcode = v
}

func (o DeviceEncryptionAes256) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceEncryptionAes256) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passcode"] = o.Passcode
	return toSerialize, nil
}

func (o *DeviceEncryptionAes256) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passcode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceEncryptionAes256 := _DeviceEncryptionAes256{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceEncryptionAes256)

	if err != nil {
		return err
	}

	*o = DeviceEncryptionAes256(varDeviceEncryptionAes256)

	return err
}

type NullableDeviceEncryptionAes256 struct {
	value *DeviceEncryptionAes256
	isSet bool
}

func (v NullableDeviceEncryptionAes256) Get() *DeviceEncryptionAes256 {
	return v.value
}

func (v *NullableDeviceEncryptionAes256) Set(val *DeviceEncryptionAes256) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceEncryptionAes256) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceEncryptionAes256) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceEncryptionAes256(val *DeviceEncryptionAes256) *NullableDeviceEncryptionAes256 {
	return &NullableDeviceEncryptionAes256{value: val, isSet: true}
}

func (v NullableDeviceEncryptionAes256) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceEncryptionAes256) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


