/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RangeValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RangeValues{}

// RangeValues struct for RangeValues
type RangeValues struct {
	Min float32 `json:"min"`
	Max float32 `json:"max"`
	DefaultValue float32 `json:"defaultValue"`
}

type _RangeValues RangeValues

// NewRangeValues instantiates a new RangeValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRangeValues(min float32, max float32, defaultValue float32) *RangeValues {
	this := RangeValues{}
	this.Min = min
	this.Max = max
	this.DefaultValue = defaultValue
	return &this
}

// NewRangeValuesWithDefaults instantiates a new RangeValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRangeValuesWithDefaults() *RangeValues {
	this := RangeValues{}
	return &this
}

// GetMin returns the Min field value
func (o *RangeValues) GetMin() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Min
}

// GetMinOk returns a tuple with the Min field value
// and a boolean to check if the value has been set.
func (o *RangeValues) GetMinOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Min, true
}

// SetMin sets field value
func (o *RangeValues) SetMin(v float32) {
	o.Min = v
}

// GetMax returns the Max field value
func (o *RangeValues) GetMax() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Max
}

// GetMaxOk returns a tuple with the Max field value
// and a boolean to check if the value has been set.
func (o *RangeValues) GetMaxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Max, true
}

// SetMax sets field value
func (o *RangeValues) SetMax(v float32) {
	o.Max = v
}

// GetDefaultValue returns the DefaultValue field value
func (o *RangeValues) GetDefaultValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value
// and a boolean to check if the value has been set.
func (o *RangeValues) GetDefaultValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultValue, true
}

// SetDefaultValue sets field value
func (o *RangeValues) SetDefaultValue(v float32) {
	o.DefaultValue = v
}

func (o RangeValues) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RangeValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["min"] = o.Min
	toSerialize["max"] = o.Max
	toSerialize["defaultValue"] = o.DefaultValue
	return toSerialize, nil
}

func (o *RangeValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"min",
		"max",
		"defaultValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRangeValues := _RangeValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRangeValues)

	if err != nil {
		return err
	}

	*o = RangeValues(varRangeValues)

	return err
}

type NullableRangeValues struct {
	value *RangeValues
	isSet bool
}

func (v NullableRangeValues) Get() *RangeValues {
	return v.value
}

func (v *NullableRangeValues) Set(val *RangeValues) {
	v.value = val
	v.isSet = true
}

func (v NullableRangeValues) IsSet() bool {
	return v.isSet
}

func (v *NullableRangeValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRangeValues(val *RangeValues) *NullableRangeValues {
	return &NullableRangeValues{value: val, isSet: true}
}

func (v NullableRangeValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRangeValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


