/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZixiListener type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZixiListener{}

// ZixiListener struct for ZixiListener
type ZixiListener struct {
	ZixiListener ZixiListenerTransportProtocol `json:"zixiListener"`
}

type _ZixiListener ZixiListener

// NewZixiListener instantiates a new ZixiListener object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZixiListener(zixiListener ZixiListenerTransportProtocol) *ZixiListener {
	this := ZixiListener{}
	this.ZixiListener = zixiListener
	return &this
}

// NewZixiListenerWithDefaults instantiates a new ZixiListener object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZixiListenerWithDefaults() *ZixiListener {
	this := ZixiListener{}
	return &this
}

// GetZixiListener returns the ZixiListener field value
func (o *ZixiListener) GetZixiListener() ZixiListenerTransportProtocol {
	if o == nil {
		var ret ZixiListenerTransportProtocol
		return ret
	}

	return o.ZixiListener
}

// GetZixiListenerOk returns a tuple with the ZixiListener field value
// and a boolean to check if the value has been set.
func (o *ZixiListener) GetZixiListenerOk() (*ZixiListenerTransportProtocol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZixiListener, true
}

// SetZixiListener sets field value
func (o *ZixiListener) SetZixiListener(v ZixiListenerTransportProtocol) {
	o.ZixiListener = v
}

func (o ZixiListener) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZixiListener) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zixiListener"] = o.ZixiListener
	return toSerialize, nil
}

func (o *ZixiListener) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zixiListener",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZixiListener := _ZixiListener{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZixiListener)

	if err != nil {
		return err
	}

	*o = ZixiListener(varZixiListener)

	return err
}

type NullableZixiListener struct {
	value *ZixiListener
	isSet bool
}

func (v NullableZixiListener) Get() *ZixiListener {
	return v.value
}

func (v *NullableZixiListener) Set(val *ZixiListener) {
	v.value = val
	v.isSet = true
}

func (v NullableZixiListener) IsSet() bool {
	return v.isSet
}

func (v *NullableZixiListener) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZixiListener(val *ZixiListener) *NullableZixiListener {
	return &NullableZixiListener{value: val, isSet: true}
}

func (v NullableZixiListener) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZixiListener) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


