/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"fmt"
)

// HealthLevel the model 'HealthLevel'
type HealthLevel string

// List of healthLevel
const (
	HEALTHY HealthLevel = "HEALTHY"
	DEGRADED HealthLevel = "DEGRADED"
	CRITICAL HealthLevel = "CRITICAL"
)

// All allowed values of HealthLevel enum
var AllowedHealthLevelEnumValues = []HealthLevel{
	"HEALTHY",
	"DEGRADED",
	"CRITICAL",
}

func (v *HealthLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HealthLevel(value)
	for _, existing := range AllowedHealthLevelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid HealthLevel", value)
}

// NewHealthLevelFromValue returns a pointer to a valid HealthLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHealthLevelFromValue(v string) (*HealthLevel, error) {
	ev := HealthLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HealthLevel: valid values are %v", v, AllowedHealthLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HealthLevel) IsValid() bool {
	for _, existing := range AllowedHealthLevelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to healthLevel value
func (v HealthLevel) Ptr() *HealthLevel {
	return &v
}

type NullableHealthLevel struct {
	value *HealthLevel
	isSet bool
}

func (v NullableHealthLevel) Get() *HealthLevel {
	return v.value
}

func (v *NullableHealthLevel) Set(val *HealthLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthLevel(val *HealthLevel) *NullableHealthLevel {
	return &NullableHealthLevel{value: val, isSet: true}
}

func (v NullableHealthLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

