/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RistListener type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RistListener{}

// RistListener struct for RistListener
type RistListener struct {
	RistListener RistListenerTransportProtocol `json:"ristListener"`
}

type _RistListener RistListener

// NewRistListener instantiates a new RistListener object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRistListener(ristListener RistListenerTransportProtocol) *RistListener {
	this := RistListener{}
	this.RistListener = ristListener
	return &this
}

// NewRistListenerWithDefaults instantiates a new RistListener object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRistListenerWithDefaults() *RistListener {
	this := RistListener{}
	return &this
}

// GetRistListener returns the RistListener field value
func (o *RistListener) GetRistListener() RistListenerTransportProtocol {
	if o == nil {
		var ret RistListenerTransportProtocol
		return ret
	}

	return o.RistListener
}

// GetRistListenerOk returns a tuple with the RistListener field value
// and a boolean to check if the value has been set.
func (o *RistListener) GetRistListenerOk() (*RistListenerTransportProtocol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RistListener, true
}

// SetRistListener sets field value
func (o *RistListener) SetRistListener(v RistListenerTransportProtocol) {
	o.RistListener = v
}

func (o RistListener) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RistListener) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ristListener"] = o.RistListener
	return toSerialize, nil
}

func (o *RistListener) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ristListener",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRistListener := _RistListener{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRistListener)

	if err != nil {
		return err
	}

	*o = RistListener(varRistListener)

	return err
}

type NullableRistListener struct {
	value *RistListener
	isSet bool
}

func (v NullableRistListener) Get() *RistListener {
	return v.value
}

func (v *NullableRistListener) Set(val *RistListener) {
	v.value = val
	v.isSet = true
}

func (v NullableRistListener) IsSet() bool {
	return v.isSet
}

func (v *NullableRistListener) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRistListener(val *RistListener) *NullableRistListener {
	return &NullableRistListener{value: val, isSet: true}
}

func (v NullableRistListener) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRistListener) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


