/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReportActualConfigurationResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportActualConfigurationResponseContent{}

// ReportActualConfigurationResponseContent struct for ReportActualConfigurationResponseContent
type ReportActualConfigurationResponseContent struct {
	Success bool `json:"success"`
	State string `json:"state"`
	Message string `json:"message"`
	Error *ErrorDetails `json:"error,omitempty"`
}

type _ReportActualConfigurationResponseContent ReportActualConfigurationResponseContent

// NewReportActualConfigurationResponseContent instantiates a new ReportActualConfigurationResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportActualConfigurationResponseContent(success bool, state string, message string) *ReportActualConfigurationResponseContent {
	this := ReportActualConfigurationResponseContent{}
	this.Success = success
	this.State = state
	this.Message = message
	return &this
}

// NewReportActualConfigurationResponseContentWithDefaults instantiates a new ReportActualConfigurationResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportActualConfigurationResponseContentWithDefaults() *ReportActualConfigurationResponseContent {
	this := ReportActualConfigurationResponseContent{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ReportActualConfigurationResponseContent) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ReportActualConfigurationResponseContent) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ReportActualConfigurationResponseContent) SetSuccess(v bool) {
	o.Success = v
}

// GetState returns the State field value
func (o *ReportActualConfigurationResponseContent) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ReportActualConfigurationResponseContent) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ReportActualConfigurationResponseContent) SetState(v string) {
	o.State = v
}

// GetMessage returns the Message field value
func (o *ReportActualConfigurationResponseContent) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ReportActualConfigurationResponseContent) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ReportActualConfigurationResponseContent) SetMessage(v string) {
	o.Message = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ReportActualConfigurationResponseContent) GetError() ErrorDetails {
	if o == nil || IsNil(o.Error) {
		var ret ErrorDetails
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportActualConfigurationResponseContent) GetErrorOk() (*ErrorDetails, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ReportActualConfigurationResponseContent) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ErrorDetails and assigns it to the Error field.
func (o *ReportActualConfigurationResponseContent) SetError(v ErrorDetails) {
	o.Error = &v
}

func (o ReportActualConfigurationResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportActualConfigurationResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["state"] = o.State
	toSerialize["message"] = o.Message
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *ReportActualConfigurationResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"state",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportActualConfigurationResponseContent := _ReportActualConfigurationResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportActualConfigurationResponseContent)

	if err != nil {
		return err
	}

	*o = ReportActualConfigurationResponseContent(varReportActualConfigurationResponseContent)

	return err
}

type NullableReportActualConfigurationResponseContent struct {
	value *ReportActualConfigurationResponseContent
	isSet bool
}

func (v NullableReportActualConfigurationResponseContent) Get() *ReportActualConfigurationResponseContent {
	return v.value
}

func (v *NullableReportActualConfigurationResponseContent) Set(val *ReportActualConfigurationResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableReportActualConfigurationResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableReportActualConfigurationResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportActualConfigurationResponseContent(val *ReportActualConfigurationResponseContent) *NullableReportActualConfigurationResponseContent {
	return &NullableReportActualConfigurationResponseContent{value: val, isSet: true}
}

func (v NullableReportActualConfigurationResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportActualConfigurationResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


