/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZixiCaller type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZixiCaller{}

// ZixiCaller struct for ZixiCaller
type ZixiCaller struct {
	ZixiCaller ZixiCallerTransportProtocol `json:"zixiCaller"`
}

type _ZixiCaller ZixiCaller

// NewZixiCaller instantiates a new ZixiCaller object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZixiCaller(zixiCaller ZixiCallerTransportProtocol) *ZixiCaller {
	this := ZixiCaller{}
	this.ZixiCaller = zixiCaller
	return &this
}

// NewZixiCallerWithDefaults instantiates a new ZixiCaller object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZixiCallerWithDefaults() *ZixiCaller {
	this := ZixiCaller{}
	return &this
}

// GetZixiCaller returns the ZixiCaller field value
func (o *ZixiCaller) GetZixiCaller() ZixiCallerTransportProtocol {
	if o == nil {
		var ret ZixiCallerTransportProtocol
		return ret
	}

	return o.ZixiCaller
}

// GetZixiCallerOk returns a tuple with the ZixiCaller field value
// and a boolean to check if the value has been set.
func (o *ZixiCaller) GetZixiCallerOk() (*ZixiCallerTransportProtocol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZixiCaller, true
}

// SetZixiCaller sets field value
func (o *ZixiCaller) SetZixiCaller(v ZixiCallerTransportProtocol) {
	o.ZixiCaller = v
}

func (o ZixiCaller) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZixiCaller) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zixiCaller"] = o.ZixiCaller
	return toSerialize, nil
}

func (o *ZixiCaller) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zixiCaller",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZixiCaller := _ZixiCaller{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZixiCaller)

	if err != nil {
		return err
	}

	*o = ZixiCaller(varZixiCaller)

	return err
}

type NullableZixiCaller struct {
	value *ZixiCaller
	isSet bool
}

func (v NullableZixiCaller) Get() *ZixiCaller {
	return v.value
}

func (v *NullableZixiCaller) Set(val *ZixiCaller) {
	v.value = val
	v.isSet = true
}

func (v NullableZixiCaller) IsSet() bool {
	return v.isSet
}

func (v *NullableZixiCaller) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZixiCaller(val *ZixiCaller) *NullableZixiCaller {
	return &NullableZixiCaller{value: val, isSet: true}
}

func (v NullableZixiCaller) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZixiCaller) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


