/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceConfiguration{}

// DeviceConfiguration struct for DeviceConfiguration
type DeviceConfiguration struct {
	Channels []ChannelConfiguration `json:"channels"`
	SimpleSettings []IdAndValue `json:"simpleSettings,omitempty"`
}

type _DeviceConfiguration DeviceConfiguration

// NewDeviceConfiguration instantiates a new DeviceConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceConfiguration(channels []ChannelConfiguration) *DeviceConfiguration {
	this := DeviceConfiguration{}
	this.Channels = channels
	return &this
}

// NewDeviceConfigurationWithDefaults instantiates a new DeviceConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceConfigurationWithDefaults() *DeviceConfiguration {
	this := DeviceConfiguration{}
	return &this
}

// GetChannels returns the Channels field value
func (o *DeviceConfiguration) GetChannels() []ChannelConfiguration {
	if o == nil {
		var ret []ChannelConfiguration
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *DeviceConfiguration) GetChannelsOk() ([]ChannelConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *DeviceConfiguration) SetChannels(v []ChannelConfiguration) {
	o.Channels = v
}

// GetSimpleSettings returns the SimpleSettings field value if set, zero value otherwise.
func (o *DeviceConfiguration) GetSimpleSettings() []IdAndValue {
	if o == nil || IsNil(o.SimpleSettings) {
		var ret []IdAndValue
		return ret
	}
	return o.SimpleSettings
}

// GetSimpleSettingsOk returns a tuple with the SimpleSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceConfiguration) GetSimpleSettingsOk() ([]IdAndValue, bool) {
	if o == nil || IsNil(o.SimpleSettings) {
		return nil, false
	}
	return o.SimpleSettings, true
}

// HasSimpleSettings returns a boolean if a field has been set.
func (o *DeviceConfiguration) HasSimpleSettings() bool {
	if o != nil && !IsNil(o.SimpleSettings) {
		return true
	}

	return false
}

// SetSimpleSettings gets a reference to the given []IdAndValue and assigns it to the SimpleSettings field.
func (o *DeviceConfiguration) SetSimpleSettings(v []IdAndValue) {
	o.SimpleSettings = v
}

func (o DeviceConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channels"] = o.Channels
	if !IsNil(o.SimpleSettings) {
		toSerialize["simpleSettings"] = o.SimpleSettings
	}
	return toSerialize, nil
}

func (o *DeviceConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceConfiguration := _DeviceConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceConfiguration)

	if err != nil {
		return err
	}

	*o = DeviceConfiguration(varDeviceConfiguration)

	return err
}

type NullableDeviceConfiguration struct {
	value *DeviceConfiguration
	isSet bool
}

func (v NullableDeviceConfiguration) Get() *DeviceConfiguration {
	return v.value
}

func (v *NullableDeviceConfiguration) Set(val *DeviceConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceConfiguration(val *DeviceConfiguration) *NullableDeviceConfiguration {
	return &NullableDeviceConfiguration{value: val, isSet: true}
}

func (v NullableDeviceConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


