/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"fmt"
)

// SupportedProtocol the model 'SupportedProtocol'
type SupportedProtocol string

// List of SupportedProtocol
const (
	SRT_LISTENER SupportedProtocol = "SRT_LISTENER"
	SRT_CALLER SupportedProtocol = "SRT_CALLER"
	ZIXI_LISTENER SupportedProtocol = "ZIXI_LISTENER"
	ZIXI_CALLER SupportedProtocol = "ZIXI_CALLER"
	RIST_CALLER SupportedProtocol = "RIST_CALLER"
	RIST_LISTENER SupportedProtocol = "RIST_LISTENER"
)

// All allowed values of SupportedProtocol enum
var AllowedSupportedProtocolEnumValues = []SupportedProtocol{
	"SRT_LISTENER",
	"SRT_CALLER",
	"ZIXI_LISTENER",
	"ZIXI_CALLER",
	"RIST_CALLER",
	"RIST_LISTENER",
}

func (v *SupportedProtocol) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SupportedProtocol(value)
	for _, existing := range AllowedSupportedProtocolEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SupportedProtocol", value)
}

// NewSupportedProtocolFromValue returns a pointer to a valid SupportedProtocol
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSupportedProtocolFromValue(v string) (*SupportedProtocol, error) {
	ev := SupportedProtocol(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SupportedProtocol: valid values are %v", v, AllowedSupportedProtocolEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SupportedProtocol) IsValid() bool {
	for _, existing := range AllowedSupportedProtocolEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SupportedProtocol value
func (v SupportedProtocol) Ptr() *SupportedProtocol {
	return &v
}

type NullableSupportedProtocol struct {
	value *SupportedProtocol
	isSet bool
}

func (v NullableSupportedProtocol) Get() *SupportedProtocol {
	return v.value
}

func (v *NullableSupportedProtocol) Set(val *SupportedProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedProtocol(val *SupportedProtocol) *NullableSupportedProtocol {
	return &NullableSupportedProtocol{value: val, isSet: true}
}

func (v NullableSupportedProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

