/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RistListenerTransportProtocol type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RistListenerTransportProtocol{}

// RistListenerTransportProtocol struct for RistListenerTransportProtocol
type RistListenerTransportProtocol struct {
	StreamId *RistStreamIdentifier `json:"streamId,omitempty"`
	Port float32 `json:"port"`
	MinimumLatencyMilliseconds float32 `json:"minimumLatencyMilliseconds"`
	Encryption *DeviceEncryption `json:"encryption,omitempty"`
	Interface *string `json:"interface,omitempty"`
}

type _RistListenerTransportProtocol RistListenerTransportProtocol

// NewRistListenerTransportProtocol instantiates a new RistListenerTransportProtocol object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRistListenerTransportProtocol(port float32, minimumLatencyMilliseconds float32) *RistListenerTransportProtocol {
	this := RistListenerTransportProtocol{}
	this.Port = port
	this.MinimumLatencyMilliseconds = minimumLatencyMilliseconds
	return &this
}

// NewRistListenerTransportProtocolWithDefaults instantiates a new RistListenerTransportProtocol object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRistListenerTransportProtocolWithDefaults() *RistListenerTransportProtocol {
	this := RistListenerTransportProtocol{}
	var minimumLatencyMilliseconds float32 = 3000
	this.MinimumLatencyMilliseconds = minimumLatencyMilliseconds
	return &this
}

// GetStreamId returns the StreamId field value if set, zero value otherwise.
func (o *RistListenerTransportProtocol) GetStreamId() RistStreamIdentifier {
	if o == nil || IsNil(o.StreamId) {
		var ret RistStreamIdentifier
		return ret
	}
	return *o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RistListenerTransportProtocol) GetStreamIdOk() (*RistStreamIdentifier, bool) {
	if o == nil || IsNil(o.StreamId) {
		return nil, false
	}
	return o.StreamId, true
}

// HasStreamId returns a boolean if a field has been set.
func (o *RistListenerTransportProtocol) HasStreamId() bool {
	if o != nil && !IsNil(o.StreamId) {
		return true
	}

	return false
}

// SetStreamId gets a reference to the given RistStreamIdentifier and assigns it to the StreamId field.
func (o *RistListenerTransportProtocol) SetStreamId(v RistStreamIdentifier) {
	o.StreamId = &v
}

// GetPort returns the Port field value
func (o *RistListenerTransportProtocol) GetPort() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *RistListenerTransportProtocol) GetPortOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *RistListenerTransportProtocol) SetPort(v float32) {
	o.Port = v
}

// GetMinimumLatencyMilliseconds returns the MinimumLatencyMilliseconds field value
func (o *RistListenerTransportProtocol) GetMinimumLatencyMilliseconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MinimumLatencyMilliseconds
}

// GetMinimumLatencyMillisecondsOk returns a tuple with the MinimumLatencyMilliseconds field value
// and a boolean to check if the value has been set.
func (o *RistListenerTransportProtocol) GetMinimumLatencyMillisecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumLatencyMilliseconds, true
}

// SetMinimumLatencyMilliseconds sets field value
func (o *RistListenerTransportProtocol) SetMinimumLatencyMilliseconds(v float32) {
	o.MinimumLatencyMilliseconds = v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *RistListenerTransportProtocol) GetEncryption() DeviceEncryption {
	if o == nil || IsNil(o.Encryption) {
		var ret DeviceEncryption
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RistListenerTransportProtocol) GetEncryptionOk() (*DeviceEncryption, bool) {
	if o == nil || IsNil(o.Encryption) {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *RistListenerTransportProtocol) HasEncryption() bool {
	if o != nil && !IsNil(o.Encryption) {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given DeviceEncryption and assigns it to the Encryption field.
func (o *RistListenerTransportProtocol) SetEncryption(v DeviceEncryption) {
	o.Encryption = &v
}

// GetInterface returns the Interface field value if set, zero value otherwise.
func (o *RistListenerTransportProtocol) GetInterface() string {
	if o == nil || IsNil(o.Interface) {
		var ret string
		return ret
	}
	return *o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RistListenerTransportProtocol) GetInterfaceOk() (*string, bool) {
	if o == nil || IsNil(o.Interface) {
		return nil, false
	}
	return o.Interface, true
}

// HasInterface returns a boolean if a field has been set.
func (o *RistListenerTransportProtocol) HasInterface() bool {
	if o != nil && !IsNil(o.Interface) {
		return true
	}

	return false
}

// SetInterface gets a reference to the given string and assigns it to the Interface field.
func (o *RistListenerTransportProtocol) SetInterface(v string) {
	o.Interface = &v
}

func (o RistListenerTransportProtocol) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RistListenerTransportProtocol) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StreamId) {
		toSerialize["streamId"] = o.StreamId
	}
	toSerialize["port"] = o.Port
	toSerialize["minimumLatencyMilliseconds"] = o.MinimumLatencyMilliseconds
	if !IsNil(o.Encryption) {
		toSerialize["encryption"] = o.Encryption
	}
	if !IsNil(o.Interface) {
		toSerialize["interface"] = o.Interface
	}
	return toSerialize, nil
}

func (o *RistListenerTransportProtocol) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"port",
		"minimumLatencyMilliseconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRistListenerTransportProtocol := _RistListenerTransportProtocol{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRistListenerTransportProtocol)

	if err != nil {
		return err
	}

	*o = RistListenerTransportProtocol(varRistListenerTransportProtocol)

	return err
}

type NullableRistListenerTransportProtocol struct {
	value *RistListenerTransportProtocol
	isSet bool
}

func (v NullableRistListenerTransportProtocol) Get() *RistListenerTransportProtocol {
	return v.value
}

func (v *NullableRistListenerTransportProtocol) Set(val *RistListenerTransportProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableRistListenerTransportProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableRistListenerTransportProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRistListenerTransportProtocol(val *RistListenerTransportProtocol) *NullableRistListenerTransportProtocol {
	return &NullableRistListenerTransportProtocol{value: val, isSet: true}
}

func (v NullableRistListenerTransportProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRistListenerTransportProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


