/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceEncryptionAes128 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceEncryptionAes128{}

// DeviceEncryptionAes128 struct for DeviceEncryptionAes128
type DeviceEncryptionAes128 struct {
	// A 32-character hexadecimal string.
	Passcode string `json:"passcode" validate:"regexp=^[a-fA-F0-9]+$"`
}

type _DeviceEncryptionAes128 DeviceEncryptionAes128

// NewDeviceEncryptionAes128 instantiates a new DeviceEncryptionAes128 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceEncryptionAes128(passcode string) *DeviceEncryptionAes128 {
	this := DeviceEncryptionAes128{}
	this.Passcode = passcode
	return &this
}

// NewDeviceEncryptionAes128WithDefaults instantiates a new DeviceEncryptionAes128 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceEncryptionAes128WithDefaults() *DeviceEncryptionAes128 {
	this := DeviceEncryptionAes128{}
	return &this
}

// GetPasscode returns the Passcode field value
func (o *DeviceEncryptionAes128) GetPasscode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passcode
}

// GetPasscodeOk returns a tuple with the Passcode field value
// and a boolean to check if the value has been set.
func (o *DeviceEncryptionAes128) GetPasscodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passcode, true
}

// SetPasscode sets field value
func (o *DeviceEncryptionAes128) SetPasscode(v string) {
	o.Passcode = v
}

func (o DeviceEncryptionAes128) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceEncryptionAes128) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passcode"] = o.Passcode
	return toSerialize, nil
}

func (o *DeviceEncryptionAes128) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passcode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceEncryptionAes128 := _DeviceEncryptionAes128{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceEncryptionAes128)

	if err != nil {
		return err
	}

	*o = DeviceEncryptionAes128(varDeviceEncryptionAes128)

	return err
}

type NullableDeviceEncryptionAes128 struct {
	value *DeviceEncryptionAes128
	isSet bool
}

func (v NullableDeviceEncryptionAes128) Get() *DeviceEncryptionAes128 {
	return v.value
}

func (v *NullableDeviceEncryptionAes128) Set(val *DeviceEncryptionAes128) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceEncryptionAes128) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceEncryptionAes128) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceEncryptionAes128(val *DeviceEncryptionAes128) *NullableDeviceEncryptionAes128 {
	return &NullableDeviceEncryptionAes128{value: val, isSet: true}
}

func (v NullableDeviceEncryptionAes128) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceEncryptionAes128) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


