/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZixiCallerTransportProtocol type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZixiCallerTransportProtocol{}

// ZixiCallerTransportProtocol struct for ZixiCallerTransportProtocol
type ZixiCallerTransportProtocol struct {
	StreamId string `json:"streamId"`
	Ip string `json:"ip"`
	Port float32 `json:"port"`
	MinimumLatencyMilliseconds float32 `json:"minimumLatencyMilliseconds"`
	Encryption *DeviceEncryption `json:"encryption,omitempty"`
}

type _ZixiCallerTransportProtocol ZixiCallerTransportProtocol

// NewZixiCallerTransportProtocol instantiates a new ZixiCallerTransportProtocol object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZixiCallerTransportProtocol(streamId string, ip string, port float32, minimumLatencyMilliseconds float32) *ZixiCallerTransportProtocol {
	this := ZixiCallerTransportProtocol{}
	this.StreamId = streamId
	this.Ip = ip
	this.Port = port
	this.MinimumLatencyMilliseconds = minimumLatencyMilliseconds
	return &this
}

// NewZixiCallerTransportProtocolWithDefaults instantiates a new ZixiCallerTransportProtocol object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZixiCallerTransportProtocolWithDefaults() *ZixiCallerTransportProtocol {
	this := ZixiCallerTransportProtocol{}
	var minimumLatencyMilliseconds float32 = 3000
	this.MinimumLatencyMilliseconds = minimumLatencyMilliseconds
	return &this
}

// GetStreamId returns the StreamId field value
func (o *ZixiCallerTransportProtocol) GetStreamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value
// and a boolean to check if the value has been set.
func (o *ZixiCallerTransportProtocol) GetStreamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StreamId, true
}

// SetStreamId sets field value
func (o *ZixiCallerTransportProtocol) SetStreamId(v string) {
	o.StreamId = v
}

// GetIp returns the Ip field value
func (o *ZixiCallerTransportProtocol) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *ZixiCallerTransportProtocol) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *ZixiCallerTransportProtocol) SetIp(v string) {
	o.Ip = v
}

// GetPort returns the Port field value
func (o *ZixiCallerTransportProtocol) GetPort() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *ZixiCallerTransportProtocol) GetPortOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *ZixiCallerTransportProtocol) SetPort(v float32) {
	o.Port = v
}

// GetMinimumLatencyMilliseconds returns the MinimumLatencyMilliseconds field value
func (o *ZixiCallerTransportProtocol) GetMinimumLatencyMilliseconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MinimumLatencyMilliseconds
}

// GetMinimumLatencyMillisecondsOk returns a tuple with the MinimumLatencyMilliseconds field value
// and a boolean to check if the value has been set.
func (o *ZixiCallerTransportProtocol) GetMinimumLatencyMillisecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumLatencyMilliseconds, true
}

// SetMinimumLatencyMilliseconds sets field value
func (o *ZixiCallerTransportProtocol) SetMinimumLatencyMilliseconds(v float32) {
	o.MinimumLatencyMilliseconds = v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *ZixiCallerTransportProtocol) GetEncryption() DeviceEncryption {
	if o == nil || IsNil(o.Encryption) {
		var ret DeviceEncryption
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZixiCallerTransportProtocol) GetEncryptionOk() (*DeviceEncryption, bool) {
	if o == nil || IsNil(o.Encryption) {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *ZixiCallerTransportProtocol) HasEncryption() bool {
	if o != nil && !IsNil(o.Encryption) {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given DeviceEncryption and assigns it to the Encryption field.
func (o *ZixiCallerTransportProtocol) SetEncryption(v DeviceEncryption) {
	o.Encryption = &v
}

func (o ZixiCallerTransportProtocol) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZixiCallerTransportProtocol) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["streamId"] = o.StreamId
	toSerialize["ip"] = o.Ip
	toSerialize["port"] = o.Port
	toSerialize["minimumLatencyMilliseconds"] = o.MinimumLatencyMilliseconds
	if !IsNil(o.Encryption) {
		toSerialize["encryption"] = o.Encryption
	}
	return toSerialize, nil
}

func (o *ZixiCallerTransportProtocol) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"streamId",
		"ip",
		"port",
		"minimumLatencyMilliseconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZixiCallerTransportProtocol := _ZixiCallerTransportProtocol{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZixiCallerTransportProtocol)

	if err != nil {
		return err
	}

	*o = ZixiCallerTransportProtocol(varZixiCallerTransportProtocol)

	return err
}

type NullableZixiCallerTransportProtocol struct {
	value *ZixiCallerTransportProtocol
	isSet bool
}

func (v NullableZixiCallerTransportProtocol) Get() *ZixiCallerTransportProtocol {
	return v.value
}

func (v *NullableZixiCallerTransportProtocol) Set(val *ZixiCallerTransportProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableZixiCallerTransportProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableZixiCallerTransportProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZixiCallerTransportProtocol(val *ZixiCallerTransportProtocol) *NullableZixiCallerTransportProtocol {
	return &NullableZixiCallerTransportProtocol{value: val, isSet: true}
}

func (v NullableZixiCallerTransportProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZixiCallerTransportProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


