/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReportActualConfigurationRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportActualConfigurationRequestContent{}

// ReportActualConfigurationRequestContent struct for ReportActualConfigurationRequestContent
type ReportActualConfigurationRequestContent struct {
	Configuration DeviceConfiguration `json:"configuration"`
}

type _ReportActualConfigurationRequestContent ReportActualConfigurationRequestContent

// NewReportActualConfigurationRequestContent instantiates a new ReportActualConfigurationRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportActualConfigurationRequestContent(configuration DeviceConfiguration) *ReportActualConfigurationRequestContent {
	this := ReportActualConfigurationRequestContent{}
	this.Configuration = configuration
	return &this
}

// NewReportActualConfigurationRequestContentWithDefaults instantiates a new ReportActualConfigurationRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportActualConfigurationRequestContentWithDefaults() *ReportActualConfigurationRequestContent {
	this := ReportActualConfigurationRequestContent{}
	return &this
}

// GetConfiguration returns the Configuration field value
func (o *ReportActualConfigurationRequestContent) GetConfiguration() DeviceConfiguration {
	if o == nil {
		var ret DeviceConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *ReportActualConfigurationRequestContent) GetConfigurationOk() (*DeviceConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *ReportActualConfigurationRequestContent) SetConfiguration(v DeviceConfiguration) {
	o.Configuration = v
}

func (o ReportActualConfigurationRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportActualConfigurationRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configuration"] = o.Configuration
	return toSerialize, nil
}

func (o *ReportActualConfigurationRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportActualConfigurationRequestContent := _ReportActualConfigurationRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportActualConfigurationRequestContent)

	if err != nil {
		return err
	}

	*o = ReportActualConfigurationRequestContent(varReportActualConfigurationRequestContent)

	return err
}

type NullableReportActualConfigurationRequestContent struct {
	value *ReportActualConfigurationRequestContent
	isSet bool
}

func (v NullableReportActualConfigurationRequestContent) Get() *ReportActualConfigurationRequestContent {
	return v.value
}

func (v *NullableReportActualConfigurationRequestContent) Set(val *ReportActualConfigurationRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableReportActualConfigurationRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableReportActualConfigurationRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportActualConfigurationRequestContent(val *ReportActualConfigurationRequestContent) *NullableReportActualConfigurationRequestContent {
	return &NullableReportActualConfigurationRequestContent{value: val, isSet: true}
}

func (v NullableReportActualConfigurationRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportActualConfigurationRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


