/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectResponseContent{}

// ConnectResponseContent struct for ConnectResponseContent
type ConnectResponseContent struct {
	Success bool `json:"success"`
	State string `json:"state"`
	Message string `json:"message"`
	Error *ErrorDetails `json:"error,omitempty"`
	DeviceId *string `json:"deviceId,omitempty"`
	Region *string `json:"region,omitempty"`
	PairingCode *string `json:"pairingCode,omitempty"`
	Expires *float32 `json:"expires,omitempty"`
}

type _ConnectResponseContent ConnectResponseContent

// NewConnectResponseContent instantiates a new ConnectResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectResponseContent(success bool, state string, message string) *ConnectResponseContent {
	this := ConnectResponseContent{}
	this.Success = success
	this.State = state
	this.Message = message
	return &this
}

// NewConnectResponseContentWithDefaults instantiates a new ConnectResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectResponseContentWithDefaults() *ConnectResponseContent {
	this := ConnectResponseContent{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ConnectResponseContent) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ConnectResponseContent) SetSuccess(v bool) {
	o.Success = v
}

// GetState returns the State field value
func (o *ConnectResponseContent) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ConnectResponseContent) SetState(v string) {
	o.State = v
}

// GetMessage returns the Message field value
func (o *ConnectResponseContent) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ConnectResponseContent) SetMessage(v string) {
	o.Message = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ConnectResponseContent) GetError() ErrorDetails {
	if o == nil || IsNil(o.Error) {
		var ret ErrorDetails
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetErrorOk() (*ErrorDetails, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ConnectResponseContent) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ErrorDetails and assigns it to the Error field.
func (o *ConnectResponseContent) SetError(v ErrorDetails) {
	o.Error = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *ConnectResponseContent) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *ConnectResponseContent) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *ConnectResponseContent) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ConnectResponseContent) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ConnectResponseContent) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ConnectResponseContent) SetRegion(v string) {
	o.Region = &v
}

// GetPairingCode returns the PairingCode field value if set, zero value otherwise.
func (o *ConnectResponseContent) GetPairingCode() string {
	if o == nil || IsNil(o.PairingCode) {
		var ret string
		return ret
	}
	return *o.PairingCode
}

// GetPairingCodeOk returns a tuple with the PairingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetPairingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PairingCode) {
		return nil, false
	}
	return o.PairingCode, true
}

// HasPairingCode returns a boolean if a field has been set.
func (o *ConnectResponseContent) HasPairingCode() bool {
	if o != nil && !IsNil(o.PairingCode) {
		return true
	}

	return false
}

// SetPairingCode gets a reference to the given string and assigns it to the PairingCode field.
func (o *ConnectResponseContent) SetPairingCode(v string) {
	o.PairingCode = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *ConnectResponseContent) GetExpires() float32 {
	if o == nil || IsNil(o.Expires) {
		var ret float32
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectResponseContent) GetExpiresOk() (*float32, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *ConnectResponseContent) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given float32 and assigns it to the Expires field.
func (o *ConnectResponseContent) SetExpires(v float32) {
	o.Expires = &v
}

func (o ConnectResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["state"] = o.State
	toSerialize["message"] = o.Message
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.PairingCode) {
		toSerialize["pairingCode"] = o.PairingCode
	}
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	return toSerialize, nil
}

func (o *ConnectResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"state",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectResponseContent := _ConnectResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectResponseContent)

	if err != nil {
		return err
	}

	*o = ConnectResponseContent(varConnectResponseContent)

	return err
}

type NullableConnectResponseContent struct {
	value *ConnectResponseContent
	isSet bool
}

func (v NullableConnectResponseContent) Get() *ConnectResponseContent {
	return v.value
}

func (v *NullableConnectResponseContent) Set(val *ConnectResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectResponseContent(val *ConnectResponseContent) *NullableConnectResponseContent {
	return &NullableConnectResponseContent{value: val, isSet: true}
}

func (v NullableConnectResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


