/*
CddService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cddmodels

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TransportProtocol - struct for TransportProtocol
type TransportProtocol struct {
	RistCaller *RistCaller
	RistListener *RistListener
	SrtCaller *SrtCaller
	SrtListener *SrtListener
	ZixiCaller *ZixiCaller
	ZixiListener *ZixiListener
}

// RistCallerAsTransportProtocol is a convenience function that returns RistCaller wrapped in TransportProtocol
func RistCallerAsTransportProtocol(v *RistCaller) TransportProtocol {
	return TransportProtocol{
		RistCaller: v,
	}
}

// RistListenerAsTransportProtocol is a convenience function that returns RistListener wrapped in TransportProtocol
func RistListenerAsTransportProtocol(v *RistListener) TransportProtocol {
	return TransportProtocol{
		RistListener: v,
	}
}

// SrtCallerAsTransportProtocol is a convenience function that returns SrtCaller wrapped in TransportProtocol
func SrtCallerAsTransportProtocol(v *SrtCaller) TransportProtocol {
	return TransportProtocol{
		SrtCaller: v,
	}
}

// SrtListenerAsTransportProtocol is a convenience function that returns SrtListener wrapped in TransportProtocol
func SrtListenerAsTransportProtocol(v *SrtListener) TransportProtocol {
	return TransportProtocol{
		SrtListener: v,
	}
}

// ZixiCallerAsTransportProtocol is a convenience function that returns ZixiCaller wrapped in TransportProtocol
func ZixiCallerAsTransportProtocol(v *ZixiCaller) TransportProtocol {
	return TransportProtocol{
		ZixiCaller: v,
	}
}

// ZixiListenerAsTransportProtocol is a convenience function that returns ZixiListener wrapped in TransportProtocol
func ZixiListenerAsTransportProtocol(v *ZixiListener) TransportProtocol {
	return TransportProtocol{
		ZixiListener: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TransportProtocol) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RistCaller
	err = newStrictDecoder(data).Decode(&dst.RistCaller)
	if err == nil {
		jsonRistCaller, _ := json.Marshal(dst.RistCaller)
		if string(jsonRistCaller) == "{}" { // empty struct
			dst.RistCaller = nil
		} else {
			if err = validator.Validate(dst.RistCaller); err != nil {
				dst.RistCaller = nil
			} else {
				match++
			}
		}
	} else {
		dst.RistCaller = nil
	}

	// try to unmarshal data into RistListener
	err = newStrictDecoder(data).Decode(&dst.RistListener)
	if err == nil {
		jsonRistListener, _ := json.Marshal(dst.RistListener)
		if string(jsonRistListener) == "{}" { // empty struct
			dst.RistListener = nil
		} else {
			if err = validator.Validate(dst.RistListener); err != nil {
				dst.RistListener = nil
			} else {
				match++
			}
		}
	} else {
		dst.RistListener = nil
	}

	// try to unmarshal data into SrtCaller
	err = newStrictDecoder(data).Decode(&dst.SrtCaller)
	if err == nil {
		jsonSrtCaller, _ := json.Marshal(dst.SrtCaller)
		if string(jsonSrtCaller) == "{}" { // empty struct
			dst.SrtCaller = nil
		} else {
			if err = validator.Validate(dst.SrtCaller); err != nil {
				dst.SrtCaller = nil
			} else {
				match++
			}
		}
	} else {
		dst.SrtCaller = nil
	}

	// try to unmarshal data into SrtListener
	err = newStrictDecoder(data).Decode(&dst.SrtListener)
	if err == nil {
		jsonSrtListener, _ := json.Marshal(dst.SrtListener)
		if string(jsonSrtListener) == "{}" { // empty struct
			dst.SrtListener = nil
		} else {
			if err = validator.Validate(dst.SrtListener); err != nil {
				dst.SrtListener = nil
			} else {
				match++
			}
		}
	} else {
		dst.SrtListener = nil
	}

	// try to unmarshal data into ZixiCaller
	err = newStrictDecoder(data).Decode(&dst.ZixiCaller)
	if err == nil {
		jsonZixiCaller, _ := json.Marshal(dst.ZixiCaller)
		if string(jsonZixiCaller) == "{}" { // empty struct
			dst.ZixiCaller = nil
		} else {
			if err = validator.Validate(dst.ZixiCaller); err != nil {
				dst.ZixiCaller = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZixiCaller = nil
	}

	// try to unmarshal data into ZixiListener
	err = newStrictDecoder(data).Decode(&dst.ZixiListener)
	if err == nil {
		jsonZixiListener, _ := json.Marshal(dst.ZixiListener)
		if string(jsonZixiListener) == "{}" { // empty struct
			dst.ZixiListener = nil
		} else {
			if err = validator.Validate(dst.ZixiListener); err != nil {
				dst.ZixiListener = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZixiListener = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RistCaller = nil
		dst.RistListener = nil
		dst.SrtCaller = nil
		dst.SrtListener = nil
		dst.ZixiCaller = nil
		dst.ZixiListener = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TransportProtocol)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TransportProtocol)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TransportProtocol) MarshalJSON() ([]byte, error) {
	if src.RistCaller != nil {
		return json.Marshal(&src.RistCaller)
	}

	if src.RistListener != nil {
		return json.Marshal(&src.RistListener)
	}

	if src.SrtCaller != nil {
		return json.Marshal(&src.SrtCaller)
	}

	if src.SrtListener != nil {
		return json.Marshal(&src.SrtListener)
	}

	if src.ZixiCaller != nil {
		return json.Marshal(&src.ZixiCaller)
	}

	if src.ZixiListener != nil {
		return json.Marshal(&src.ZixiListener)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TransportProtocol) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.RistCaller != nil {
		return obj.RistCaller
	}

	if obj.RistListener != nil {
		return obj.RistListener
	}

	if obj.SrtCaller != nil {
		return obj.SrtCaller
	}

	if obj.SrtListener != nil {
		return obj.SrtListener
	}

	if obj.ZixiCaller != nil {
		return obj.ZixiCaller
	}

	if obj.ZixiListener != nil {
		return obj.ZixiListener
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TransportProtocol) GetActualInstanceValue() (interface{}) {
	if obj.RistCaller != nil {
		return *obj.RistCaller
	}

	if obj.RistListener != nil {
		return *obj.RistListener
	}

	if obj.SrtCaller != nil {
		return *obj.SrtCaller
	}

	if obj.SrtListener != nil {
		return *obj.SrtListener
	}

	if obj.ZixiCaller != nil {
		return *obj.ZixiCaller
	}

	if obj.ZixiListener != nil {
		return *obj.ZixiListener
	}

	// all schemas are nil
	return nil
}

type NullableTransportProtocol struct {
	value *TransportProtocol
	isSet bool
}

func (v NullableTransportProtocol) Get() *TransportProtocol {
	return v.value
}

func (v *NullableTransportProtocol) Set(val *TransportProtocol) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportProtocol) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportProtocol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportProtocol(val *TransportProtocol) *NullableTransportProtocol {
	return &NullableTransportProtocol{value: val, isSet: true}
}

func (v NullableTransportProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportProtocol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


